[BUGFIX] Fix localization record merging logic
FluidTYPO3/flux pull request #2198
Opened 2024-12-04 16:02 UTC by monosize

Updated the logic to correctly merge localized records by checking for the existence of '_LOCALIZED_UID' in the $contentObject data. The $record was missing the '_LOCALIZED_UID' field, and therefore proper data localization never occurred.

This change ensures that records are only merged if a valid localized version is available.

I extracted $this->recoredService->getSingle(...) from the array_merge function because on my system this never merged the localized record. Therefore, getSingle is stored in a separate variable and then, if available, merged.

2024-12-04 16:04 UTC, monosize commented
Tested with TYPO3 12.4.23

2024-12-04 16:06 UTC, monosize commented
Maybe the content from the $contentObject can be used completely – without array_merge; I haven't tested that yet.

2024-12-04 16:14 UTC, monosize commented
I ran a test that uses $contentObject->data.
It worked for me. Is there any reason not to use it directly?


```php
        if ($contentObject->data['_LOCALIZED_UID'] ?? false) {
            return $contentObject->data;
//            $test = $this->recordService->getSingle(
//                (string) $this->getFluxTableName(),
//                '*',
//                $contentObject->data['_LOCALIZED_UID']
//            );
//            $record = array_merge(
//                $record,
//                $test ?: $record
//            );
        }
        return $record;
```

2024-12-09 14:06 UTC, NamelessCoder requested changes
> Is there any reason not to use it (`cObj->data`) directly?

This may be different on TYPO3 versions, but in at least some of my testing back when writing the method, `cObj->data` was not trustworthy. It behaved differently in content vs. pages, and in `INT` and cached contexts. In some cases it even contained the data of a totally different element - which would be really bad.

So we do need to use `$record` and we do need to perform the overlay. At least for now.

2025-10-17 09:04 UTC, NamelessCoder commented
Sorry about the delay here. I believe this is fixed, either by https://github.com/FluidTYPO3/flux/pull/2253 whcih fixes the overlaying that happens inside the record service, or by https://github.com/FluidTYPO3/flux/commit/f71fe74e848718c3972a73af9cccb815c3aad183 which circumvents the record lookup to use the cObj data in almost all cases.

2025-10-17 09:04 UTC, closed without merging